In [4]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('tracks.csv')
df2=pd.read_csv('artists.csv')

In [3]:
df1.head()

,id,name,popularity,duration_ms,explicit,artists,id_artists,release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,35iwgR4jXetI318WEWsa1Q,Carve,6,126903,0,['Uli'],['45tIt06XoI0Iio4LBEVpls'],1922-02-22,0.645,0.4450,0,-13.338,1,0.4510,0.674,0.7440,0.151,0.127,104.851,3
1,021ht4sdgPcrDgSk7JTbKY,Capítulo 2.16 - Banquero Anarquista,0,98200,0,['Fernando Pessoa'],['14jtPCOoNZwquk5wd9DxrY'],1922-06-01,0.695,0.2630,0,-22.136,1,0.9570,0.797,0.0000,0.148,0.655,102.009,1
2,07A5yehtSnoedViJAZkNnc,Vivo para Quererte - Remasterizado,0,181640,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],1922-03-21,0.434,0.1770,1,-21.180,1,0.0512,0.994,0.0218,0.212,0.457,130.418,5
3,08FmqUhxtyLTn6pAh6bk45,El Prisionero - Remasterizado,0,176907,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],1922-03-21,0.321,0.0946,7,-27.961,1,0.0504,0.995,0.9180,0.104,0.397,169.980,3
4,08y9GfoqCWfOGsKdwojr5e,Lady of the Evening,0,163080,0,['Dick Haymes'],['3BiJGZsyX9sJchTqcSA7Su'],1922,0.402,0.1580,3,-16.900,0,0.0390,0.989,0.1300,0.311,0.196,103.220,4

In [6]:
def normalize_dates(df1, chunk_size=100000):
    total_rows = len(df1)
    for start in range(0, total_rows, chunk_size):
        end = start + chunk_size
        print(f"Processing rows {start} to {end}")
        chunk = df1.iloc[start:end]
        df1.loc[start:end, 'release_date'] = chunk['release_date'].apply(normalize_date)
        print(f"Processed {end if end < total_rows else total_rows} rows out of {total_rows}")
    return df1

def normalize_date(date):
    if pd.to_datetime(date, errors='coerce', format='%Y-%m-%d') is not pd.NaT:
        return date
    elif pd.to_datetime(date, errors='coerce', format='%m/%d/%Y') is not pd.NaT:
        return pd.to_datetime(date, format='%m/%d/%Y').strftime('%Y-%m-%d')
    elif pd.to_datetime(date, errors='coerce', format='%Y') is not pd.NaT:
        return f"{date}-01-01"
    else:
        return np.nan

df1 = normalize_dates(df1, chunk_size=100000)

Processing rows 0 to 100000
Processed 100000 rows out of 586672
Processing rows 100000 to 200000
Processed 200000 rows out of 586672
Processing rows 200000 to 300000
Processed 300000 rows out of 586672
Processing rows 300000 to 400000
Processed 400000 rows out of 586672
Processing rows 400000 to 500000
Processed 500000 rows out of 586672
Processing rows 500000 to 600000
Processed 586672 rows out of 586672

In [9]:
df1.release_date

0         1922-02-22
1         1922-06-01
2         1922-03-21
3         1922-03-21
4         1922-01-01
             ...
586667    2020-09-26
586668    2020-10-21
586669    2020-09-02
586670    2021-03-05
586671    2015-07-01
Name: release_date, Length: 586672, dtype: object

In [8]:
df1['artists'] = df1['artists'].str.strip("[]").str.replace("'", "")
df1['id_artists'] = df1['id_artists'].str.strip("[]").str.replace("'", "")

In [10]:
df1.artists
df1.id_artists

0                                 45tIt06XoI0Iio4LBEVpls
1                                 14jtPCOoNZwquk5wd9DxrY
2                                 5LiOoJbxVSAMkBS2fUm3X2
3                                 5LiOoJbxVSAMkBS2fUm3X2
4                                 3BiJGZsyX9sJchTqcSA7Su
                               ...
586667                            1QLBXKM5GCpyQQSVMNZqrZ
586668                            1dy5WNgIKQU6ezkpZs4y8z
586669                            37M5pPGs6V1fchFJSgCguX
586670    4jGPdu95icCKVF31CcFKbS, 5ebPSE9YI5aLeZ1Z2gkqjn
586671                            0i4Qda0k4nf7jnNHmSNpYv
Name: id_artists, Length: 586672, dtype: object

In [13]:
df1.isnull()

,id,name,popularity,duration_ms,explicit,artists,id_artists,release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586667,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
586668,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
586669,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
586670,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
586671,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

-- Remove el with more than 3 null attributes

In [16]:
import pandas as pd

def remove_rows_with_nulls(df1, threshold=3):
    return df1[df1.isnull().sum(axis=1) < threshold]

Remove names with non-ASCII characters

In [19]:
import re

def clean_names(df, column):
    def clean_text(text):
        return re.sub(r'[^\x00-\x7F]+', 'UNKNOWN', text)

    df[column] = df[column].apply(lambda x: clean_text(x) if isinstance(x, str) else x)
    return df

df1 = clean_names(df1, 'name')

In [20]:
# Save the cleaned DataFrame to a CSV file
df1.to_csv('tracks_cleaned.csv', index=False)

In [21]:
df2.head()

,id,followers,genres,name,popularity
0,0DheY5irMjBUeLybbCUEZ2,0.0,[],Armid & Amir Zare Pashai feat. Sara Rouzbehani,0
1,0DlhY15l3wsrnlfGio2bjU,5.0,[],ปูนา ภาวิณี,0
2,0DmRESX2JknGPQyO15yxg7,0.0,[],Sadaa,0
3,0DmhnbHjm1qw6NCYPeZNgJ,0.0,[],Tra'gruda,0
4,0Dn11fWM7vHQ3rinvWEl4E,2.0,[],Ioannis Panoutsopoulos,0

Remove names with non-ASCII characters

In [23]:
import re

def clean_names(df2, column):
    def clean_text(text):
        return re.sub(r'[^\x00-\x7F]+', 'UNKNOWN', text)

    df2[column] = df2[column].apply(lambda x: clean_text(x) if isinstance(x, str) else x)
    return df2

df2 = clean_names(df2, 'name')

In [24]:
#Remove brackets from genres column
def clean_genres(df2, column):
    def clean_genre(genre):
        if pd.isna(genre):
            return genre
        genre_str = str(genre)
        if genre_str.strip('[]').strip() == '':
            return 'Unknown'
        genre_str = re.sub(r'[\[\]\'"]+', '', genre_str)
        return genre_str
    
    df2[column] = df2[column].apply(clean_genre)
    return df2

df2 = clean_genres(df2, 'genres')

In [25]:
df2.to_csv('artists_cleaned.csv', index=False)