<span style="color:brown; font-weight:bold;">BRONZE LAYER</span>

In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('charts.csv')

In [7]:
null_trend_rows = df[df['trend'].isnull()]

print(null_trend_rows)

Empty DataFrame
Columns: [title, rank, date, artist, url, region, chart, trend, streams]
Index: []

In [9]:
df.head(10)

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0
5,Traicionera,6,2017-01-01,Sebastian Yatra,https://open.spotify.com/track/5J1c3M4EldCfNxX...,Argentina,top200,MOVE_DOWN,151140.0
6,Cuando Se Pone a Bailar,7,2017-01-01,Rombai,https://open.spotify.com/track/1MpKZi1zTXpERKw...,Argentina,top200,MOVE_DOWN,148369.0
7,Otra vez (feat. J Balvin),8,2017-01-01,Zion & Lennox,https://open.spotify.com/track/3QwBODjSEzelZyV...,Argentina,top200,MOVE_DOWN,143004.0
8,La Bicicleta,9,2017-01-01,"Carlos Vives, Shakira",https://open.spotify.com/track/0sXvAOmXgjR2QUq...,Argentina,top200,MOVE_UP,126389.0
9,Dile Que Tu Me Quieres,10,2017-01-01,Ozuna,https://open.spotify.com/track/20ZAJdsKB5IGbGj...,Argentina,top200,MOVE_DOWN,112012.0

It was given that the value of streams is NULL when the chart column is "viral50". In order to have room for faster data 
processing we can replace this unrecognizable definition into null values to use in functions or models.

In [14]:
search_string = "viral50"
matching_rows = df[df['chart'].str.contains(search_string, na=False)]
print(matching_rows)

                                  title  rank        date  \
12808                              Boys    13  2017-08-01
12965                           Hold Me    19  2017-08-01
13781                         Hola Hola    40  2017-08-01
14042                           Cuídate     4  2017-08-01
14092                              Boys    13  2017-08-01
...                                 ...   ...         ...
26173509                            BYE    46  2021-07-31
26173510                        Pillars    47  2021-07-31
26173511                   Gái Độc Thân    48  2021-07-31
26173512  Renegade (feat. Taylor Swift)    49  2021-07-31
26173513                Letter to Jarad    50  2021-07-31

                             artist  \
12808                    Charli XCX
12965                         R3HAB
13781                          KARD
14042                       Zetazen
14092                    Charli XCX
...                             ...
26173509                      Jaden
26173510                     My Anh
26173511                      Tlinh
26173512            Big Red Machine
26173513  LRN Slime, Shiloh Dynasty

                                                        url      region  \
12808     https://open.spotify.com/track/5o4yGlG0PfeVUa6...      Latvia
12965     https://open.spotify.com/track/2a9xGmpgNyNz9QV...  Luxembourg
13781     https://open.spotify.com/track/3VC1IEz9M1txlMS...        Peru
14042     https://open.spotify.com/track/0WgnbqlHieZmdYa...       Spain
14092     https://open.spotify.com/track/5o4yGlG0PfeVUa6...      Taiwan
...                                                     ...         ...
26173509  https://open.spotify.com/track/3OUyyDN7EZrL7i0...     Vietnam
26173510  https://open.spotify.com/track/6eky30oFiQbHUAT...     Vietnam
26173511  https://open.spotify.com/track/2klsSb2iTfgDh95...     Vietnam
26173512  https://open.spotify.com/track/1aU1wpYBSpP0M6I...     Vietnam
26173513  https://open.spotify.com/track/508QhA2SncMbh5C...     Vietnam

            chart          trend  streams
12808     viral50        MOVE_UP      NaN
12965     viral50      MOVE_DOWN      NaN
13781     viral50      NEW_ENTRY      NaN
14042     viral50  SAME_POSITION      NaN
14092     viral50      MOVE_DOWN      NaN
...           ...            ...      ...
26173509  viral50        MOVE_UP      NaN
26173510  viral50      NEW_ENTRY      NaN
26173511  viral50      MOVE_DOWN      NaN
26173512  viral50      MOVE_DOWN      NaN
26173513  viral50      MOVE_DOWN      NaN

[5851610 rows x 9 columns]

In [16]:
count_matching_rows = df['chart'].str.contains("viral50", na=False).sum()

print(f"Total count of rows containing the word 'viral 50': {count_matching_rows}")

Total count of rows containing the word 'viral 50': 5851610

In [18]:
if df.isna().sum().sum() == 0:
    print("No missing values.")
else:
    print("There are missing values in the data.")
    print("\nMissing values per column:")
    print(df.isna().sum())

There are missing values in the data.

Missing values per column:
title           11
rank             0
date             0
artist          18
url              0
region           0
chart            0
trend            0
streams    5851610
dtype: int64

In [22]:
# Replace values containing 'viral50' with NaN
affected_rows = df['chart'].str.contains("viral50", na=False)
df.loc[affected_rows, 'chart'] = np.nan

# Count the number of affected rows
count_affected_rows = affected_rows.sum()

print(f"Total count of rows where 'viral50' was replaced with NaN: {count_affected_rows}")
print("\nUpdated DataFrame:")
print(df)

Total count of rows where 'viral50' was replaced with NaN: 5851610

Updated DataFrame:
                                  title  rank        date  \
0               Chantaje (feat. Maluma)     1  2017-01-01
1           Vente Pa' Ca (feat. Maluma)     2  2017-01-01
2            Reggaetón Lento (Bailemos)     3  2017-01-01
3                                Safari     4  2017-01-01
4                           Shaky Shaky     5  2017-01-01
...                                 ...   ...         ...
26173509                            BYE    46  2021-07-31
26173510                        Pillars    47  2021-07-31
26173511                   Gái Độc Thân    48  2021-07-31
26173512  Renegade (feat. Taylor Swift)    49  2021-07-31
26173513                Letter to Jarad    50  2021-07-31

                                         artist  \
0                                       Shakira
1                                  Ricky Martin
2                                          CNCO
3         J Balvin, Pharrell Williams, BIA, Sky
4                                  Daddy Yankee
...                                         ...
26173509                                  Jaden
26173510                                 My Anh
26173511                                  Tlinh
26173512                        Big Red Machine
26173513              LRN Slime, Shiloh Dynasty

                                                        url     region  \
0         https://open.spotify.com/track/6mICuAdrwEjh6Y6...  Argentina
1         https://open.spotify.com/track/7DM4BPaS7uofFul...  Argentina
2         https://open.spotify.com/track/3AEZUABDXNtecAO...  Argentina
3         https://open.spotify.com/track/6rQSrBHf7HlZjtc...  Argentina
4         https://open.spotify.com/track/58IL315gMSTD37D...  Argentina
...                                                     ...        ...
26173509  https://open.spotify.com/track/3OUyyDN7EZrL7i0...    Vietnam
26173510  https://open.spotify.com/track/6eky30oFiQbHUAT...    Vietnam
26173511  https://open.spotify.com/track/2klsSb2iTfgDh95...    Vietnam
26173512  https://open.spotify.com/track/1aU1wpYBSpP0M6I...    Vietnam
26173513  https://open.spotify.com/track/508QhA2SncMbh5C...    Vietnam

           chart          trend   streams
0         top200  SAME_POSITION  253019.0
1         top200        MOVE_UP  223988.0
2         top200      MOVE_DOWN  210943.0
3         top200  SAME_POSITION  173865.0
4         top200        MOVE_UP  153956.0
...          ...            ...       ...
26173509     NaN        MOVE_UP       NaN
26173510     NaN      NEW_ENTRY       NaN
26173511     NaN      MOVE_DOWN       NaN
26173512     NaN      MOVE_DOWN       NaN
26173513     NaN      MOVE_DOWN       NaN

[26173514 rows x 9 columns]

In [24]:
df.columns

Index(['title', 'rank', 'date', 'artist', 'url', 'region', 'chart', 'trend',
       'streams'],
      dtype='object')

In [26]:
df.dtypes

title       object
rank         int64
date        object
artist      object
url         object
region      object
chart       object
trend       object
streams    float64
dtype: object

In [28]:
# Convert date to datetime and extract components
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['day_of_week'] = df['date'].dt.dayofweek

In [30]:
df.head()

,title,rank,date,artist,url,region,chart,trend,streams,year,month,day,day_of_week
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0,2017,1,1,6
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0,2017,1,1,6
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0,2017,1,1,6
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0,2017,1,1,6
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0,2017,1,1,6

In [32]:
df.to_csv('bronzelayer_Spotify_Charts.csv', index=False)